# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 1.2
  - 1.3
  - nightly
notifications:
  email: false
after_success:
 - julia -e 'import Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'

jobs:
  allow_failures:
    - julia: nightly
  include:
    - stage: "Documentation"
      julia: 1
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                               Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip






# # Documentation: http://docs.travis-ci.com/user/languages/julia/
#
# sudo: required
# language: julia
# addons:
#   apt:
#     update: true
# os:
#   - linux
#   - osx
# julia:
#   - 1.0
#   - nightly
# matrix:
#     allow_failures:
#         - julia: nightly
# notifications:
#   email: false
# after_success:
#   - julia -e 'using Pkg, MetabolicEP; Pkg.add("Documenter"); include(joinpath("docs", "make.jl"))'
#   - julia -e 'using Pkg, MetabolicEP; Pkg.add("Coverage"); using Coverage; get(ENV,"TRAVIS_OS_NAME","")=="linux" && get(ENV,"TRAVIS_JULIA_VERSION","")=="0.7" && Codecov.submit(Codecov.process_folder())'
# branches:
#   only:
#     - master
